### ISSUE TITLE
"Load new posts" never disappears on desktop

### ISSUE THREAD

**Issue by danudwary** [bluesky-social/social-app#1009]
**Describe the bug**
When new posts are made in the Following tab, the "Load new posts" button pops up on top of posts on screen. The button never disappears until clicked or the page is refreshed. Might not be a bug, but is poor as a UI element, since this functionality is already available through the "^" icon ever-present in the lower left corner. A similar button is used on Twitter, which I assume this was intended to replicate, but the Twitter version disappears after a short period of time. Once a user follows even a few dozen active people, this button basically never goes away, and is obtrusive and unnecessary. 

1. Load the desktop client via https://bsky.app
2. Login if necessary
3. Wait for new posts to be posted
4. Wait forever while the annoying "Load new posts" button blocks the top post on the page

**Details**

 - Platform: desktop - chrome and safari browsers
 - Platform version: MacOS. Previously observed on Windows 11, but unable to confirm at the moment

**Comment by Zero3K** [comment]
I think this has been fixed in 1.46. If so, please close this issue.

**Comment by ansh** [comment]
@Zero3K Yes, this should have been fixed. Only the bottom left arrow should be persistent. It will have a blue indicator if there are new posts!

**Comment by danudwary** [comment]
I don't understand why this is closed. The "Load New Posts" button still persists on desktop. (1.49.0, according to my desktop "Settings" page)
