### ISSUE TITLE
Going forward and back in the browser loses position in the feed/tab

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/social-app#1352]
**Describe the bug**

I'm going through one of my feeds that I have pinned in the top tabs, clicking on some posts and going back to the feed. I've noticed that sometimes the app resets tab selection to the Following feed. I think I've found a way to reproduce this consistently.

**To Reproduce**

1. Select a tab in the top bar for one of the custom feeds that you have pinned.
2. Scroll down the feed a bit.
3. Click a post in the feed to go to the post details page.
4. Press "Back" in the browser to go back to the feed.
5. Now, press "Forward" in the browser to go to that post details page again.
6. And now press "Back" in the browser again.
7. You are now on the "Following" feed tab instead of the feed that you were on, and the feed will reload from the beginning when you select that tab again.

**Expected behavior**

If you select a post in the feed and then repeatedly do Back - Forward - Back - Forward etc., you should keep switching between the post details page and the feed page, keeping that feed tab selected and keeping the scroll position in the feed.

**Details**

 - Platform: macOS 12.6.8 (21G725), Safari 16.6 (17615.3.12.11.3, 17615)

**Comment by haileyok** [comment]
Pretty sure we fixed this one a long time ago lol. But feel free to tell me if not.

**Comment by brw** [comment]
@haileyok pretty sure this is still an issue. I think I've narrowed it down too. It only seems to happen when navigating Forward until there is no more forward navigation left.

If I click on any replies after navigating to a post, then press Back enough times to go all the way back to the feed, I can still press Forward and Back however much I want and the scroll position is kept, except for when I press Forward enough times to go all the way Forward to the very last post I was on. Then once I go back to the feed (either through pressing Back enough times or clicking Home in the sidebar) my scroll position is reset.

Should I open a new issue for this?

**Comment by brw** [comment]
I did some digging and I think this might be bug 2 described here https://github.com/react-navigation/react-navigation/issues/10915.

Walking through it with a debugger I can see that React Navigation's history stack gets corrupted because the internal index is not incremented/decremented when using browser navigation (in this case the index will generally stay on the last item on the stack because of that, continuously overwriting it, which explains why it's that one specifically that generally triggers the reset).

I also saw #6534 so I looked at Expo Router's fork of React Navigation as well but I'm pretty sure that one still has the same bug (semi-related: https://github.com/expo/expo/issues/31747).

**Comment by KernelLeak** [comment]
Came here to look if there's an existing bug for my scroll position on the following feed always resetting when I back out of a post then hit forward because I missed some detail in it, only to be scrolled to the top in the following feed when going back again... seems this is exactly it.

(Can't comment on the React side of things; I'm using Vue for development, but that got it's own share of navigation... "eccentricies"...)

**Comment by gaearon** [comment]
Yeah that's definitely a known bug.

**Comment by serter1** [comment]
https://github.com/user-attachments/assets/c1105ea9-c8f0-4733-b928-eaec82c2d0a0
