### ISSUE TITLE
There is no way to unfollow a user if they blocked you

### ISSUE THREAD

**Issue by Ai-rin** [bluesky-social/social-app#2028]
**Describe the bug**

Users who block me still counts as followed, but i can't unfollow them

**To Reproduce**

Have somebody block you then try to unfollow them

**Expected behavior**

Users who blocked me should still be present in the follow list so I can unfollow them.

**Details**

Build version: 1.56.0; Platform: web

**Comment by meicpalmer** [comment]
Blocking someone should make them unfollow you, so people can perform softblocks.

**Comment by Ai-rin** [comment]
> Blocking someone should make them unfollow you, so people can perform softblocks.

Either way, if i still follow somebody, they shouldn't disappear from my follow list.

**Comment by scottdotweb** [comment]
Could we get confirmation from the team that this will be addressed, please?

**Comment by surfdude29** [comment]
This absolutely should be fixed so that there's a way to do it through the app, but in the meantime you can do it using this great tool:

https://cleanfollow-bsky.pages.dev/

**Comment by mschwendener** [comment]
Not sure if this is related: 
I have unfollowed https://bsky.app/profile/gladlib.bsky.social but still see their posts in the OnlyPosts feed. 
This has been going on for a while; following & unfollowing again does not fix it.

**Comment by X1Vi** [comment]
Guys I have added a fix and added a video I hope it is to your expectations.

**Comment by eddieoz** [comment]
Is there a chance this could resolve the inability to unfollow people, potentially due to asynchronous issues like this: https://github.com/bluesky-social/atproto/issues/3256 ?

**Comment by welaughindoors** [comment]
> Is there a chance this could resolve the inability to unfollow people, potentially due to asynchronous issues like this: [bluesky-social/atproto#3256](https://github.com/bluesky-social/atproto/issues/3256) ?

Echoing this, experiencing the same issues and its infuriating to have hundreds of people (likely bots) that I cannot unfollow and are cluttering my feed.
