### ISSUE TITLE
Option for notification when a followed user posts

### ISSUE THREAD

**Issue by gitanO0** [bluesky-social/social-app#2050]
Would love to see a per-followed-user option to enable notifications for when the followed user posts.  This is the one piece of functionality that's keeping me using "X".  Please consider this so I can finally ditch X.

**Comment by ccrowles** [comment]
Was about to request the same thing, it's probably the feature I miss the most from Twitter. I follow a lot of people so stuff can get lost, so I would love to have an option to enable notifications for when a specific user posts something or quote-retweets something.

**Comment by surfdude29** [comment]
I’m also really looking forward to having this feature built-in to the official app.

In the meantime, if you have an iPhone or iPad you could have a look at Skeets, which is a Bluesky app for iOS/iPadOS by an independent developer. It has this feature (and many other great ones too), and it works pretty well in my experience.

Although, I can’t remember if notifications when a user posts are a Pro feature or not, perhaps the developer @seboslaw could help?

In any case, the Pro features are well worth the fairly small cost imo.

- [Skeets app website](https://www.skeetsapp.com/)
- [Skeets app profile on Bluesky](https://bsky.app/profile/skeetsapp.com)

**Comment by ccrowles** [comment]
Thanks for the recommendation, but unfortunately I use Bluesky on pc and on my android phone.

**Comment by seboslaw** [comment]
@surfdude29 thx for recommending Skeets!
Yeah, post notifications are a subscription feature for the time being.

**Comment by SuperIchi** [comment]
This is also for me the one feature missing for me to fully migrate over from Twitter.
Hope we hear about this one soon. :)

**Comment by Zulith** [comment]
This is an essential feature for many of us. Please boost this.

**Comment by bittersweetCavalier** [comment]
This post was made nearly a year ago, please add this, Bluesky!!!

**Comment by DenowRammy** [comment]
This is a pretty necessary feature. Given the state of the current project, I think it'd be worth it to spend some time implementing this feature at this point.

**Comment by joelfichter** [comment]
Wanted to boost this because as others have said, this is really the only thing that is currently keeping me from ditching Twitter entirely. It's honestly a necessary feature for me to use the app.

**Comment by zebancodes** [comment]
bumping this because this would be the final thing that let's me permanently cut twitter out of my life!

**Comment by that1crzywhtguy** [comment]
Tried to switch to bluesky, but this feature is a must for me. It's the primary way I interacted with twitter. 95%+ of my usage. If this one feature was added, I'd 100% roll to bluesky

**Comment by VitalNonsense** [comment]
As more accounts I follow migrate to bluesky, the absence of this feature is becoming a larger issue for me.

**Comment by Vervious** [comment]
Hi, bumping this also, I think it's a must-have for me.

**Comment by Whathaveyudone** [comment]
This almost feels necessary for the usage, Instagram has it too

**Comment by tinytransfem** [comment]
This is an absolute must-have. I'm really trying to fully swap from Twitter to Bluesky but 99% of times I only open social media apps when I get notifs so without this feature the app just doesn't work for me.

**Comment by jblaze03** [comment]
Add me as another one who feels like this is THE killer feature to get people over here. I never scroll through my feed I just look at tweets from a selected few accounts I follow which all show up in my notification bar (Android).

Without this feature I will never really use bluesky since it doesn't actively engage me. It will just be another app on my phone that never get opened and eventually just get deleted since it is unused.

**Comment by mikailmm** [comment]
I agree with other people here. Bumping this.

**Comment by mrbydangel** [comment]
Another bump. Essential feature to fully switch from Twitter.

**Comment by le-avion** [comment]
It's kind of disturbing that a year later this has not been implemented nor has it been assigned to anyone. I just joined Blusky because I want to be off the other one but I cannot do that as long as this feature is missing.

**Comment by davidfguillaume** [comment]
+1

**Comment by de-gene-rate** [comment]
Also chiming in to say this is the last thing holding me back from deleting my twitter account.

**Comment by diarzola** [comment]
This one's a must

**Comment by magic-spearmint** [comment]
Hopeful that this one can be given more priority on the roadmap.

**Comment by putch** [comment]
How tf are we supposed to develop parasocial relationships without notifications!?!?

**Comment by koppekoppe** [comment]
Some accounts I follow announce new releases of merch and stuff - most of the time, the things I want are gone by the time I check bsky. Hope you can implement this feature soon!

**Comment by iamsocoolyes** [comment]
pleeeeease implement this feature. it's essential for a lot of folks!

**Comment by lowercase-donkey** [comment]
Anecdotally, this was keeping my sister from switching for months. They're on now, but it was a big deal for them.

**Comment by SuperIchi** [comment]
> Anecdotally, this was keeping my sister from switching for months. They're on now, but it was a big deal for them.

Did they find a way to get this functionality or did they just get tired of waiting and migrated without it?

**Comment by blu3r4d0n** [comment]
> > Anecdotally, this was keeping my sister from switching for months. They're on now, but it was a big deal for them.
> 
> Did they find a way to get this functionality or did they just get tired of waiting and migrated without it?

not the person you asked, but I assume they just got tired of waiting. As of today, nearly a year after this issue was first opened, this is on the roadmap but not in active development and there's no indication of this feature request's priority. There is no native way to get notifs for specific accounts in the social application.

**Comment by itsolie** [comment]
signed in just to bump this, would love if bluesky allowed us to enable notifs when specific accounts post!

**Comment by SuperIchi** [comment]
I got added to the beta of an app that gives me this functionality. Anyone else interested can DM the person.
 https://www.reddit.com/r/BlueskySocial/comments/17co4t4/comment/lx67dao/

**Comment by BrianWendt** [comment]
I'd really like to be able to subscribe to a whooe feed, not just individual users.

**Comment by NickThrew** [comment]
I'm not above begging for this feature. let me know what I have to do.

**Comment by that1crzywhtguy** [comment]
Just got a Tsunami warning from X because I have notifications on X accounts, and no ability to have the same on BlueSky. This needs to be addressed.

**Comment by adamatic-me** [comment]
> Just got a Tsunami warning from X because I have notifications on X accounts, and no ability to have the same on BlueSky. This needs to be addressed. 

Yup, I've been watching this issue for a year now.

If emergency services and important accounts ever want to move here, this is a must have feature. 

From the outside, it seems like maybe it's a boring feature that no one wants to work on? 

Or, maybe scope creep is the enemy of shipping?

I know devs are busy, but is this real that hard on-protocol?

**Comment by that1crzywhtguy** [comment]
Amen! This is the last thing I need to delete X and remove my account forever.

**Comment by LethiferousMoose** [comment]
I just migrated a little over 100 accounts I follow to Bluesky, this feature is definitely needed to track important accounts. I was surprised by how limited the current notification system is.

**Comment by grumpymojo** [comment]
This is a must have feature for me. Use this feature on X to keep track of posters who are important to me.

**Comment by Whathaveyudone** [comment]
I’ve found an app called Bluenotify on iOS for that, it doesn’t show the images for the post but I think it’s good enough to use until the feature becomes official.
https://apps.apple.com/app/id6738239349

**Comment by grumpymojo** [comment]
This looks like it will do for now. Thanks for the tip.

**Comment by totevt78** [comment]
That precisely suffice this feature. ✅
Thanks a lot for sharing it. 🙏

**Comment by Whathaveyudone** [comment]
You’re welcome you guys! I think it’s soon coming to Android too

**Comment by LetsPlayNintendoITA2023** [comment]
following this for news on the android version

**Comment by LethiferousMoose** [comment]
It looks like Blue Notify went live for Android today. Check their website for a link to the Play Store.

**Comment by Vaesse75** [comment]
Thank you @LethiferousMoose ! This solves my problem completely!

**Comment by Robie123423** [comment]
Ik zou ook graag meldingen willen ontvangen, net zoals bij X gebeurt van personen die ik volg.

**Comment by dom6770** [comment]
Yes, please, add this feature. I truly miss it from Twitter and yet it's not even on the roadmap.

Using a second app shouldn't be necessary.

**Comment by taubsix3** [comment]
When will we get this feature? I'd love to see this <3

**Comment by PhilC813** [comment]
Just moved over from Mastodon and I was surprised to see that this isn't a feature :o

**Comment by Dyl-M** [comment]
This will be my one and only comment.
Please lock the comment section.

All messages begging for this feature do not help. They are repetitive, useless and I would like to be notified only if the development of this feature is ever considered.

Thanks in advance.

**Comment by jeffthekarlypilkboy** [comment]
@surfdude29 Implementing push notifications is something that should have been done way earlier in the SDLC for the application. It's inexcusable that this is not a feature. This feature is why I stopped using the app.

**Comment by nabelekt** [comment]
I just got on Bluesky expecting this feature to be there, wanting to follow an event, and I'm pretty disappointed it isn't.

**Comment by onemahon** [comment]
Probably worth noting to get some extra attention on it - per #7520 , push notifications don't even work *at all* for the web app.

(That means that, ironically, I currently receive push notifications about other users via BlueNotify, but NOT notifications for DMs or activity on my posts through Bluesky itself)

**Comment by Dyl-M** [comment]
@nabelekt @jeffthekarlypilkboy 
[Contributing to a project -- Learn how to contribute to a project through forking.](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project)

**Comment by surfdude29** [comment]
The devs are currently working on this, and the latest from @/pfrazee is:

> That is on the near-term tracker! (I won't promise more because a bird could hit the devs and stop it from happening but it's very nearterm)

https://bsky.app/profile/pfrazee.com/post/3lqv2xwqehk2i

**Comment by symmetricalboy** [comment]
Looks like this one can be closed! <3

**Comment by totevt78** [comment]
Good news! 🗞️🤗

It seems this issue has been resolved.

Development of this feature was carried out under #8485

Released with BlueSky [v1.104.0](https://github.com/bluesky-social/social-app/releases/tag/1.104.0)

**Comment by mozzius** [comment]
We just shipped this :)

**Comment by LethiferousMoose** [comment]
@mozzius it still doesn't seem to notify for plain Reposts, only Posts/Quote Posts. Idk if that was an intentional gap. I know BlueNotify used a separate setting for Repost notifications.

**Comment by mozzius** [comment]
Yep, I didn't know that was a feature people wanted when I was designing it. Feel free to make a new issue :)

**Comment by LethiferousMoose** [comment]
Thanks @mozzius, I left my feedback/suggestions on #8643.
