### ISSUE TITLE
Garbled generated captions for link cards

### ISSUE THREAD

**Issue by nihonmatsu** [bluesky-social/social-app#2855]
Not limited to the Web version, but the generated captions for the [link cards](https://bsky.app/profile/nihonmatsu.bsky.social/post/3kl5wpp45mb2a) are garbled.
Perhaps the special character encoding (euc-jp) used in the [original Web site](https://www.star-domain.jp/) may have affected the results.

Explanation of garbled characters (HTML)

`<div dir="auto" class="css-146c3p1 r-8akbws r-krxsd3 r-dnmrzs r-1udh08x r-1udbk01" style="-webkit-line-clamp: 3; font-size: 16px; letter-spacing: 0.25px; font-weight: 700; color: rgb(8, 10, 12);">�������ɥᥤ�� - �ʰ¥ɥᥤ������ 100�ߡ�(�ǹ�)��̵�����󥿥륵���С��դ���</div>`

`<div dir="auto" class="css-146c3p1 r-8akbws r-krxsd3 r-dnmrzs r-1udh08x r-1udbk01 r-14gqq1x" style="-webkit-line-clamp: 2; font-size: 15px; letter-spacing: 0.25px; font-weight: 400; color: rgb(8, 10, 12);">�������ɥᥤ���ϡ��ʰ¤�ǯ��������40�����ʾ����ȼ��ɥᥤ���μ�������ǽ�Ǥ���̵���ǻȤ��륵���С���ǽ�����ܡ��¿����ƥɥᥤ���Τ����Ѥ���ǽ��ICANN��ǧ�쥸���ȥ��Ǥ���</div>`

![スクリーンショット 2024-02-12 12 22 10](https://github.com/bluesky-social/atproto-website/assets/7820013/0d7db098-dbe9-4acb-8017-6b66f2d9bd05)

Best regards.

**Comment by bnewbold** [comment]
(moved this issue from `atproto-website` to `social-app`, which is closer to where this kind of problem will get resolved)


cc: @Jacob2161, presumably a cardyb or upstream API issue?

**Comment by haileyok** [comment]
@nihonmatsu This should be fixed now

![Screenshot 2024-02-15 at 11 01 39 AM](https://github.com/bluesky-social/social-app/assets/153161762/6943a9ff-601a-4df7-b832-a49b887d8f5b)

**Comment by Zero3K** [comment]
It's not fixed for me:

![image](https://github.com/bluesky-social/social-app/assets/6194332/a34f0aff-1f05-4e8d-9b9f-39358c8bb405)

**Comment by haileyok** [comment]
@Zero3K The old posts won't have changed, since that text is stored in the record. Future embeds with that (or similar) text will be good though 👍

**Comment by Zero3K** [comment]
Oh, okay.
