### ISSUE TITLE
Full screening embedded video does not work when scrolled down in notifs

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#2984]
**Describe the bug**
When scrolled down at least a page or more of view height in the notifs, attempting to full screen an embedded video in a reply completely breaks. It scrolls all the way up and then immediately breaks the embed after it goes off screen which then cancels the fullscreen which makes for a weird flicker effect.

**To Reproduce**

1. Have a lot of notifications
2. Somewhere down the way, have a reply with an embedded video
3. Attempt to fullscreen that video
4. Observe

**Expected behavior**

This to not happen.

**Screenshots**

**Details**

 - Platform: Chromium web
 - Platform version:
 - App version:

**Additional context**

**Comment by haileyok** [comment]
I think this is fixed coming up, reworked how the measurements work for the embeds. Please let me know once 1.69 is released!

**Comment by Juicysteak117** [comment]
> I think this is fixed coming up, reworked how the measurements work for the embeds. Please let me know once 1.69 is released!

Will do!

**Comment by Juicysteak117** [comment]
@haileyok Forgot to update but issue still persists. Seems to be not just notifications. Example post where it does it: https://bsky.app/profile/cirikino.bsky.social/post/3ko4rfy4g2t25

**Comment by haileyok** [comment]
Thanks for updating me on this. Really annoying situation, will have to do some digging to find a good solution.
