### ISSUE TITLE
Can you make previews more accurate?

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#3614]
Hi

It would be great if the previews for the link cards and for uploaded pictures could be more accurate. 

Link card preview 
<img width="540" alt="1" src="https://github.com/bluesky-social/social-app/assets/4497705/8b739d29-622a-4944-a904-daf610bc88f0">

How it looks after posting (picture cropped)
<img width="532" alt="2" src="https://github.com/bluesky-social/social-app/assets/4497705/0caed7b4-0cb3-4118-a222-4e926dc78ff3">

---

Uploaded picture preview 
<img width="556" alt="3" src="https://github.com/bluesky-social/social-app/assets/4497705/7681ae2d-f683-4afa-ac88-3992f6ca037d">

How it looks after posting (picture as I wanted to show it)
<img width="537" alt="4" src="https://github.com/bluesky-social/social-app/assets/4497705/1448cfcb-2593-4139-af9b-152429845e8d">
 
 Thank you

**Comment by surfdude29** [comment]
I think this has just been fixed in main by #3579, but perhaps @haileyok could confirm?

**Comment by mschwendener** [comment]
No, link card preview with uploaded picture not fixed 
![nope1](https://github.com/user-attachments/assets/110cff4b-d73b-4ec5-97c4-a59346eb8e3b)

And this has been closed, although it's not fixed 
https://github.com/bluesky-social/social-app/issues/1118

**Comment by mschwendener** [comment]
> I think the link card part has just been fixed in main by https://github.com/bluesky-social/social-app/pull/3579 

Maybe it's fixed for mobile? Not for desktop.

<img width="621" alt="screenshot_5052" src="https://github.com/user-attachments/assets/993d07fd-7e40-4782-9db0-9f21a756c838">

**Comment by mschwendener** [comment]
<img width="606" alt="screenshot_5077" src="https://github.com/user-attachments/assets/0b05d0df-24a9-4d77-b139-62f3e4ec90f3">

<img width="524" alt="screenshot_5079" src="https://github.com/user-attachments/assets/fcd256ea-0484-46cc-ab44-4d526c9332e9">

**Comment by mschwendener** [comment]
*bump* 

see also https://github.com/bluesky-social/social-app/issues/6808 and as an example https://bsky.app/profile/nhannahjones.bsky.social
