### ISSUE TITLE
search page url parameters

### ISSUE THREAD

**Issue by jonolds** [bluesky-social/social-app#3675]
When you search in the web version, the url is always "https://bsky.app/search?q=". 
This is bad because: 

1. When you refresh the browser, it goes to the empty search page (showing suggested follows) instead of updating the search. 
2. You can't save a search or share it.
3. It makes back behavior very unpredictable. I don't know how to explain this one, because I'm not sure what's happening. But if I leave the search results and then hit back, it might show the last search or it might show one several searches back.

Thanks!

**Comment by surfdude29** [comment]
It looks like this might well be improved/fixed by the changes in #3663?

**Comment by jonolds** [comment]
@surfdude29 Oh! It is improved, but still not right. The first search is captured as a url, but if you search again from the results page it reverts to "https://bsky.app/search?q=".

**Comment by surfdude29** [comment]
> @surfdude29 Oh! It is improved, but still not right. The first search is captured as a url, but if you search again from the results page it reverts to "https://bsky.app/search?q=".

That's helpful feedback, thanks. Hopefully that will be fixed when @haileyok has finished working on the PR and it's ready to go 🚀

**Comment by jonolds** [comment]
awesome! thanks so much!!!

**Comment by gaearon** [comment]
Thanks for the report! Does the behavior on https://social-app-pr-3663.onrender.com/ match your expectations?

**Comment by jonolds** [comment]
sorry for not replying, I hate that github doesn't have notifications for submitted issues. It's late, but yeah! it was perfect. thanks!

**Comment by jonolds** [comment]
sorry for not replying, I hate that github doesn't have notifications for submitted issues. but yeah! it was perfect. thanks!
