### ISSUE TITLE
Viewing Likes tab/page for an account/profile/user with no liked posts causes infinite spinner/loop XHR [web]

### ISSUE THREAD

**Issue by surfdude29** [bluesky-social/social-app#4879]
**Describe the bug**

When you're logged into an account which hasn't liked any posts yet and you view the **Likes** tab on web, it loads infinitely.

**To Reproduce**

1. On **bsky.app** log into an account which hasn't liked any posts yet (I created a temporary alt to make the screen recording below).
2. View the **Likes** tab on the account's profile.
3. The spinner is displayed infinitely.

**Expected behavior**

The spinner should stop and the **No posts yet.** screen should be displayed.

**Screenshots**

https://github.com/user-attachments/assets/5cf66480-8d14-47d7-a7c7-7f80b3b2da3a

**Details**

 - Platform: iPadOS Safari and Brave on Ubuntu
 - Platform version: 16.6.1
 - App version: 1.92.1

**EDIT:** Updated description to make clearer and reflect that this still occurs on 1.92.1 on web.

**Comment by surfdude29** [comment]
Also, I noticed that the infinite spinner shows up if you've only liked a few posts and you scroll down and reach the bottom of the page when you're on your **Likes** tab.

**Comment by heikadog** [comment]
This also shows up on the regular Bluesky web app.

**Comment by haileyok** [comment]
I cannot reproduce this right now. There was momentarily an appview bug that we fixed shortly after it got deployed, so can you try again?

@heikadog If you're seeing this currently it is likely a separate issue. Would be good if you could record a video!

**Comment by surfdude29** [comment]
> This also shows up on the regular Bluesky web app.

Thanks for pointing this out 🙏

I've corrected the description.

**Comment by surfdude29** [comment]
> I cannot reproduce this right now. There was momentarily an appview bug that we fixed shortly after it got deployed, so can you try again?

I can still reproduce this on **bsky.app** in Safari (iPadOS 16.6.1) but not in 1.89 of the iOS/iPadOS app.

**Comment by haileyok** [comment]
Wait, does this only happen on iPad? Also @heikadog

**Comment by surfdude29** [comment]
I can reproduce this in:

- Safari on iPhone 7 running iOS 15.8.3
- Safari on iPad (9th generation) running iPadOS 16.6.1
- Brave Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit) on Ubuntu 20.04.6 LTS
- Chrome 127.0.6533.99 (Official Build) (64-bit) on Ubuntu 20.04.6 LTS

Screen recording from my iPhone:

https://github.com/user-attachments/assets/e777b16b-edcb-4843-a9b5-364b234f405f

**Comment by haileyok** [comment]
Ah, missed that it was specifically the likes tab. Thanks.

**Comment by nucleartux** [comment]
If anyone is interested, I did a quick investigation.
I suspect a bug on the ATProto side because, for some reason, `app.bsky.feed.getActorLikes` returns a `cursor` even if the `feed` is empty.
Unfortunately, I was unable to reproduce it with a local ATProto instance. To be more specific, I know such a response is possible if liked posts are deleted, but this is a different case.

**Comment by roni-castro** [comment]
### Scenarios to Reproduce the Error (tested on version 1.94.0)

**Scenario for 0 Likes:**
1. Create a new account in the app and log in.
2. Tap on the **Profile** tab.
3. Tap on the **Likes** tab.
4. You will see the spinner being rendered **50 times** 

**Scenario for Few Likes:**
1. Create a new account and log in to the app.
2. Like a few posts (e.g., 2 posts).
3. Tap on the **Profile** tab.
5. Tap on the **Likes** tab.
6. You will see the spinner being rendered **infinite times**

It seems that the `Likes` tab is facing multiple issues:

### Issue 1
The [`onEndReached`](https://github.com/bluesky-social/social-app/blob/main/src/view/com/posts/Feed.tsx#L421-L442) function is being triggered multiple times when there are very **few likes**. This results in an infinite loop of requests to the API until the user hits the API rate limit.

**Note:** The RN debugger struggles with handling infinite loops, so you can confirm this behavior by adding `console.log('fetchNextPage')` and observing that `fetchNextPage` is being called repeatedly.

Demo:  

https://github.com/user-attachments/assets/ed6de5c4-48a1-4b60-9a5e-444f718ea876

### Issue 2
When the list does not have at least [`MIN_POSTS`](https://github.com/bluesky-social/social-app/blob/main/src/state/queries/post-feed.ts#L392) items, there's a [`useEffect`](https://github.com/bluesky-social/social-app/blob/main/src/state/queries/post-feed.ts#L370-L412) that runs the logic to fetch the next page using [`query.fetchNextPage()`](https://github.com/bluesky-social/social-app/blob/main/src/state/queries/post-feed.ts#L405-L407) up to 50 times. This happens every time any property of the `query` object (`data`, `fetchStatus`, `isFetching`, `isFetchingNextPage`, etc.) changes.

### Issue 3
The API returns an invalid cursor when there are **no likes** or just a **few likes** or the **last page** for `app.bsky.feed.getActorLikes`.  
- **Expected behavior:** When a user has zero likes, the API should return `{"feed": []}`.  
- **Current behavior:** It instead returns an invalid cursor: `{"feed": [], "cursor": "3l3ejwggbzz22"}`.

This invalid cursor leads to continuous triggering of the above `useEffect` because the `query` object (returned by [`useInfiniteQuery`](https://github.com/bluesky-social/social-app/blob/main/src/state/queries/post-feed.ts#L165)) changes, causing the effect to re-run.

**Scenarios:**  
- **0 likes:** Results in exactly 50 API requests.  

https://github.com/user-attachments/assets/55d5be96-d917-408e-a293-f07cd80b6f1a  
- **Few likes:** Causes an infinite number of requests until the API rate limit is reached, likely leading to an error for the user.  

https://github.com/user-attachments/assets/1eeddbdd-8441-473b-86dd-12ce2be6f66e

- **Last page:** Causes an infinite number of requests

https://github.com/user-attachments/assets/c4e4d17b-6577-44b1-91e1-a614547256af

### Potential Workaround
A fix on the backend side would be to stop returning an invalid cursor when the API returns an empty `feed: []`. However, even with that fix, there may still be concurrency issues due to the problems described in Issues 1 and 2.

It was used in the examples below, Proxyman to intercept the api request and change it to return a valid response when `feed` is empty and an invalid cursor is returned.

- **Stop returning an invalid cursor for empty feeds (0 likes):**  

https://github.com/user-attachments/assets/fdd61e02-9a01-40e7-9a47-9061d498d323  
- **Stop returning an invalid cursor when there are only a few likes on a specific page:**  

https://github.com/user-attachments/assets/0aec5682-82b9-4de2-b481-a85a50dcfd94

**Comment by fdemir** [comment]
issue still exists on the latest version

**Comment by kidonng** [comment]
An easy mitigation may be just reducing the failsafe limit added in [`c6f9cfc` (#4863)](https://github.com/bluesky-social/social-app/pull/4863/commits/c6f9cfc2c76de1d901bef754ad27088643504825) (currently 50).

**Comment by Doeke** [comment]
Is this the same issue as not being able to load more than 32 liked posts on app or with api? Even if I use the api `app.bsky.feed.getActorLikes` it just returns cursors with empty feed lists once it gets past the first 32, I cannot fetch older likes at all
