### ISSUE TITLE
No more notifications after update (1.90.1)

### ISSUE THREAD

**Issue by minegameYTB** [bluesky-social/social-app#5226]
**Describe the bug**
When updating the app, I recently noticed that notifications were no longer working properly with the latest version on Android

**To Reproduce**

1. Update bluesky on Android

2. Repost or like a post

**Expected behavior**
Have the notification appear in Android notifications

**Details**

 - Platform: Samsung Galaxy a13 (SM-A137F/DSN)
 - Platform version: Android 14 (OneUi 6.1)
 - App version: Bluesky 1.90.1

**Comment by zersorger** [comment]
I've got the same issue and thought it was my fault.

Device: RMX3085 ( Realme 8)
Android: 13
App version:  1.90.1

**Comment by Tim-Gra** [comment]
Same issue here.


Platform: Samsung Xcover6 (SM-G736B/DN)
Platform version: Android 14 (OneUi 6.1)
App version: Bluesky 1.90.1

**Comment by surfdude29** [comment]
FYI @pfrazee [commented here](https://github.com/bluesky-social/social-app/issues/789#issuecomment-2341331892):

> Google changed up some APIs, we're in the process of updating our clients

**Comment by haileyok** [comment]
This should be resolved now, was a google api issue that we had to fix up.

**Comment by bilbonotry** [comment]
Not resolved for me. App version 1.95.0, android 15 pixel 7a. I never had any notification since I installed. Notification and background permissions given.
