### ISSUE TITLE
Like Button Display Issue

### ISSUE THREAD

**Issue by tlaverdure** [bluesky-social/social-app#5854]
### Steps to Reproduce

The like button has a outline/ring around it when a post is liked. Don't see this on the web.

### Attachments

![IMG_0275](https://github.com/user-attachments/assets/97cb7da4-044e-49ae-ad08-6fab932336d1)

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 15 Pro Max

### What version of the app are you using?

Latest

**Comment by surfdude29** [comment]
Yeah I find this very annoying too.

**Comment by tlaverdure** [comment]
Looks fixed now

**Comment by tlaverdure** [comment]
Looks fixed now

**Comment by surfdude29** [comment]
Interesting, I'm definitely still seeing it 🤔

![IMG_1982](https://github.com/user-attachments/assets/d5e69673-5417-4a87-a71b-c8abb06ab6b5)
