### ISSUE TITLE
morel.us-east.host.bsky.network is unreachable

### ISSUE THREAD

**Issue by RicardoLuis0** [bluesky-social/social-app#6140]
### Steps to Reproduce

1. Log in
2. Does not load
3. Log out
4. Loads

### Attachments

![image](https://github.com/user-attachments/assets/e4558eaf-6c87-4c32-8bac-cffa46b0361b)
![image](https://github.com/user-attachments/assets/c337fbd6-503e-4ea2-abde-1b2ece4a4e4f)

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Firefox 132.0.1

### What version of the app are you using?

Build version: 1.92.1; Bundle info: dfbfcdd (prod); Bundle date: 24110420; Platform: web

### Additional Information

This has been happening for a few days/weeks now, thought it'd just be fixed, but it hasn't

#888 and #2262 are possible duplicates, but they're old issues that haven't been updated in a year+, and seems like a cors change (#5221) was made recently (compared to the previously-mentioned issues), so i'm making a new issue

**Comment by RicardoLuis0** [comment]
checking on reddit, seems like it's been happening for ~2 weeks
https://old.reddit.com/r/BlueskySocial/comments/1gait5y/logging_in_to_bluesky_doesnt_load_any_posts/

**Comment by DavidBuchanan314** [comment]
It's likely that the requests are failing outright, rather than it being a CORS issue per se (CORS preflight is just the first thing that happens).

The network tab would likely give more insight as to *why* they're failing, but my guess would be a network connectivity issue of some kind. Can you access https://morel.us-east.host.bsky.network/ in your web browser?

**Comment by RicardoLuis0** [comment]
> It's likely that the requests are failing outright, rather than it being a CORS issue per se
seems to be the case yes, odd
![image](https://github.com/user-attachments/assets/f4ea4b1e-9a1c-472a-8fae-deff1726403c)

**Comment by RicardoLuis0** [comment]
doesn't seem to be DNS
![image](https://github.com/user-attachments/assets/b6dd6aa6-9d74-41e0-98ad-8e523711573e)
![image](https://github.com/user-attachments/assets/103c8560-5d76-4ecf-bc88-b73dad63a6cb)

**Comment by DavidBuchanan314** [comment]
I'm guessing it's a routing or filtering issue *somewhere*. Given the small number of people reporting this, I'd guess it's an issue with your ISP. Running traceroute/tracepath might provide some insight as to where (be aware that if you share output from either, you'll be giving away your IP address and ISP, which you may or may not care about privacy-wise)

**Comment by RicardoLuis0** [comment]
stops at 100.127.*, so CGNAT fucking up?

**Comment by simonorono** [comment]
This is still happening to me on Firefox 131.0.3

![image](https://github.com/user-attachments/assets/f99e00c0-85ab-44e9-9457-8ffdf822a110)

**Comment by RicardoLuis0** [comment]
could this possibly be that `morel.us-east.host.bsky.network` has blacklisted latin-american IPs used by carrier CGNAT?

**Comment by simonorono** [comment]
> could this possibly be that `morel.us-east.host.bsky.network` has blacklisted some latin-american IP ranges used by carriers for CGNAT?

I don't think so because it also happens when I use a paid VPN with servers on the USA (California, specifically).

**Comment by RicardoLuis0** [comment]
seems like this was resolved, at least for me

**Comment by simonorono** [comment]
Still not solved on my end

![image](https://github.com/user-attachments/assets/36ba89cd-4aee-4670-b08b-a1ffb1287619)

**Comment by DavidBuchanan314** [comment]
It's almost certainly an ISP issue of some kind, either with your own ISP, or one of the intermediate hops.
