### ISSUE TITLE
Uploading a GIF unexpectedly posts a JPEG

### ISSUE THREAD

**Issue by joakimcarlgren** [bluesky-social/social-app#6697]
### Steps to Reproduce

To repro
1. Upload a GIF to your post (which seems to be allowed)
2. Your post now has a JPG

Solution
Maybe either prevent the upload of anything animated, until its supported, or at least communicate that the gif will be converted to a jpg at publishing.

### What platform(s) does this occur on?

Android

### Device Info

Pixel 9 pro

### What version of the app are you using?

1.94.0.402

**Comment by arashveysi3** [comment]
can solve this. leave it to me plzzzzzzzzz

**Comment by gaearon** [comment]
This should already be fixed on main (https://main.bsky.dev/), mind checking there? Thanks.

**Comment by gaearon** [comment]
Ah apparently it should work with the video button for now. We'll unify them later.

**Comment by codeMotif** [comment]
Not fixed. In the main.bsky.dev implementation, the gif image is processed into a bilinearly-upscaled video file, vastly increasing the file size, degrading the quality, and eliminating necessary alpha channel information for any gif images that have small resolution.

**Comment by gaearon** [comment]
That's good to know. We're not expecting to be able to dive improving this anytime soon, unfortunately, so let's keep this open.

**Comment by codeMotif** [comment]
Doesn't need an improvement. Serve the original gif if it's under a certain file size, scale with CSS.

**Comment by mirh** [comment]
#6837

**Comment by rock3r** [comment]
I can repro the same issue with PNGs (e.g., images from emoji kitchen)

https://bsky.app/profile/sebastiano.dev/post/3lczbrvchwc24

**Comment by Zero3K** [comment]
*bump*
