### ISSUE TITLE
Android App - Click on Videos, crashes Application

### ISSUE THREAD

**Issue by rseiffert** [bluesky-social/social-app#7250]
### Steps to Reproduce

Use the official Android Application (last Update from Dec 20, 2024; 1.96.2.542)
Click on an embedded video
Click again to hear the audio
You hear the first milliseconds of audio
Then the app crashes

Try this video for example:
https://bsky.app/profile/cwebbonline.com/post/3lds2qur5ac2o

The system log shows nothing interesting.
It used to work in earlier versions.

### What platform(s) does this occur on?

Android

### Device Info

Galaxy S8+

### What version of the app are you using?

1.96.2.542

**Comment by gaearon** [comment]
What Android version are you on?

**Comment by rseiffert** [comment]
I have to admit, it's quite old
Android Version: 9

But it used to work until the current bluesky app update

![phone](https://github.com/user-attachments/assets/943b173f-395f-4eed-aa94-89e4f71eb0ff)

**Comment by mlocati** [comment]
Same here (Samsung Galaxy S9 with Android 10).

Here's what I have with `adb logcat`:

```
12-27 11:00:23.749  2266  2266 W .blueskyweb.ap: Accessing hidden method Landroid/view/WindowInsets$Type;->systemBars()I (blacklist, linking, denied)
12-27 11:00:23.750  2266  2266 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-27 11:00:23.752  2266  2266 E AndroidRuntime: FATAL EXCEPTION: main
12-27 11:00:23.752  2266  2266 E AndroidRuntime: Process: xyz.blueskyweb.app, PID: 2266
12-27 11:00:23.752  2266  2266 E AndroidRuntime: java.lang.NoSuchMethodError: No static method systemBars()I in class Landroid/view/WindowInsets$Type; or its super classes (declaration of 'android.view.WindowInsets$Type' appears in /system/framework/framework.jar!classes3.dex)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at expo.modules.blueskyvideo.FullscreenActivity.onCreate$lambda$2(FullscreenActivity.kt:57)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at expo.modules.blueskyvideo.FullscreenActivity.$r8$lambda$nVP74lhUSH8ughKvCDZViI2BKBI(Unknown Source:0)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at expo.modules.blueskyvideo.FullscreenActivity$$ExternalSyntheticLambda1.onApplyWindowInsets(D8$$SyntheticClass:0)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at androidx.core.view.ViewCompat$Api21Impl$1.onApplyWindowInsets(ViewCompat.java:5232)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.View.dispatchApplyWindowInsets(View.java:11285)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8208)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8220)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8210)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8220)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8210)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8220)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8210)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8220)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8210)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8220)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8210)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2462)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2570)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:732)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
12-27 11:00:23.752  2266  2266 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
12-27 11:00:23.790  2266  6482 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-27 11:00:23.790  2266  6482 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-27 11:00:23.790   779   856 D EnterpriseController: netId is 0
12-27 11:00:23.790   779   856 E Netd    : getNetworkForDns: getNetId from enterpriseCtrl is netid 0
12-27 11:00:23.790   779   856 D DnsProxyListener: DNSDBG::dns addrinfo af 2 - 10165
12-27 11:00:23.795  1872  1887 I id.app.launche: NativeAlloc concurrent copying GC freed 24760(1377KB) AllocSpace objects, 1(184KB) LOS objects, 49% free, 9428KB/18MB, paused 199us total 248.797ms
12-27 11:00:23.796   899  3020 D Debug   : !@DumpState : SHIP
12-27 11:00:23.796   899  3020 D Debug   : !@DumpState : debug level:0x4f4c
12-27 11:00:23.796   899  3020 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
12-27 11:00:23.796   899  7962 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-27 11:00:23.796   899  3020 W ActivityManager: crash : xyz.blueskyweb.app,0
12-27 11:00:23.800   899  3020 W ActivityTaskManager:   Force finishing activity xyz.blueskyweb.app/expo.modules.blueskyvideo.FullscreenActivity
12-27 11:00:23.801   899  3020 V WindowManager: Prepare app transition: transit=TRANSIT_CRASHING_ACTIVITY_CLOSE mNextAppTransition=TRANSIT_ACTIVITY_OPEN alwaysKeepCurrent=false displayId=0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6356 com.android.server.wm.DisplayContent.prepareAppTransition:6350 com.android.server.wm.ActivityStack.finishTopCrashedActivityLocked:4649 com.android.server.wm.RootActivityContainer.finishTopCrashedActivities:1217 com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities:9078 
12-27 11:00:23.803   899  3020 V WindowManager: Prepare app transition: transit=TRANSIT_ACTIVITY_CLOSE mNextAppTransition=TRANSIT_CRASHING_ACTIVITY_CLOSE alwaysKeepCurrent=false displayId=0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6356 com.android.server.wm.DisplayContent.prepareAppTransition:6350 com.android.server.wm.ActivityStack.finishActivityLocked:4877 com.android.server.wm.ActivityStack.finishActivityLocked:4773 com.android.server.wm.ActivityStack.finishTopCrashedActivityLocked:4651 
12-27 11:00:23.804   899  3020 D TspStateManagerInternal: updateDefaultValue customSetting=null
12-27 11:00:23.805   899  3020 W ActivityTaskManager:   Force finishing activity xyz.blueskyweb.app/.MainActivity
12-27 11:00:23.805   899  3020 D ActivityTaskManager: updateMinimizedState: unknown notifyReason=2
12-27 11:00:23.806   899  3020 D InputDispatcher: Focused application set to (0): abd1d12
12-27 11:00:23.811  2266  2266 I Process : Sending signal. PID: 2266 SIG: 9
```

**Comment by joewdavies** [comment]
Same here with Xiaomi Redmi Note 8 Pro, Android 10.

**Comment by vreoo** [comment]
I encountered the same issue with version `1.96.2.542`, as mentioned by @rseiffert.

After updating to the latest version, `1.96.4`, the issue no longer occurs. I can confirm that this problem has been resolved. 

It would be great if others could verify whether the issue is fixed for them as well.

**Comment by vreoo** [comment]
Is this PR Related? https://github.com/bluesky-social/social-app/pull/7292 as it was included in the [`1.69.3`](https://github.com/bluesky-social/social-app/releases/tag/1.96.3) update

**Comment by rseiffert** [comment]
I am now on **1.96.3.507** and the issue has been resolved.

**Comment by joewdavies** [comment]
Still happening for me on Android 10, Xiaomi Redmi Note 8 Pro. 

Build version: 1.96.2.542; Bundle info: d38e985 (prod); Bundle date: 24122021; Platform: android; Platform version: 29
