### ISSUE TITLE
Posts can't be archived to Internet Archive

### ISSUE THREAD

**Issue by ssg** [bluesky-social/social-app#7307]
### Steps to Reproduce

1. Save a post's page to Internet Archive (example URL: https://bsky.app/profile/ozgur-mumcu.bsky.social/post/3lehp2knm6k23)
2. Try to browse the saved copy (example URL: https://web.archive.org/web/20241229222201/https://bsky.app/profile/ozgur-mumcu.bsky.social/post/3lehp2knm6k23)
3. Observe "Oops! XRPC Not supported" error. 

### What platform(s) does this occur on?

Web (Desktop)

### What version of the app are you using?

1.96.2

**Comment by scottdotweb** [comment]
This also happens for user profiles.

Thankfully for the history of this service until now, the content *is* captured because it occurs in the HTML in triplicate. Twice in the `<head>`:

```html
<meta name="description" content="Yazmak için easy script diye bir word processor vardı. Diğer programları hatırlamıyorum. Yazdıklarını, floppy disketlere kaydediyordu. Aşivine anahtar kelime arayarak daha kolay erişiyordu. Dot matrix printer'ından çıktı alıp yazıları gazeteye evden yanılmıyorsam panasonic bir faxla gönderiyordu.">
<meta property="og:description" content="Yazmak için easy script diye bir word processor vardı. Diğer programları hatırlamıyorum. Yazdıklarını, floppy disketlere kaydediyordu. Aşivine anahtar kelime arayarak daha kolay erişiyordu. Dot matrix printer'ından çıktı alıp yazıları gazeteye evden yanılmıyorsam panasonic bir faxla gönderiyordu.">
```

And once in a `<noscript>`, along with a snobby comment:

```html
<noscript>
    <h1 lang="en">JavaScript Required</h1>
    <p lang="en">This is a heavily interactive web application, and JavaScript is required. Simple HTML interfaces are possible, but that is not what this is.
    <p lang="en">Learn more about Bluesky at <a href="https://web.archive.org/web/20241229222201/https://bsky.social/">bsky.social</a> and <a href="https://web.archive.org/web/20241229222201/https://atproto.com/">atproto.com</a>.
    <div id="bsky_post_summary">
  <h3>Post</h3>
  <p id="bsky_display_name">Özgür Mumcu</p>
  <p id="bsky_handle">ozgur-mumcu.bsky.social</p>
  <p id="bsky_did">did:plc:uafqf7p22323wgnuta6wypfd</p>
  <p id="bsky_post_text">Yazmak için easy script diye bir word processor vardı. Diğer programları hatırlamıyorum. Yazdıklarını, floppy disketlere kaydediyordu. Aşivine anahtar kelime arayarak daha kolay erişiyordu. Dot matrix printer&#39;ından çıktı alıp yazıları gazeteye evden yanılmıyorsam panasonic bir faxla gönderiyordu.</p>
  <p id="bsky_post_indexedat">2024-12-29T18:56:32.950Z</p>
</div>

  </noscript>
```

The quick way to see the content of a Wayback Machine-archived post is to put its URL into the post composer, because the meta tags will cause it to appear as a link preview. However, the status quo is not good enough at all. The comment in the `<noscript>` block is especially disappointing.

**Comment by scottdotweb** [comment]
Related?: #975

**Comment by extua** [comment]
This is also discussed in #2272

**Comment by ssg** [comment]
This seems to have been resolved. The example that I used looks alright now: https://web.archive.org/web/2/https://bsky.app/profile/ozgur-mumcu.bsky.social/post/3lehp2knm6k23

Closing this issue.

**Comment by antibot4navalny** [comment]
The issue is still outstanding:

1) consistent "XRPCNotSupported" for some user profiles:
https://web.archive.org/web/20260421162130/https://bsky.app/profile/tayirdurden.bsky.social

2) only first seconds of videos are archived—but not full video:
https://web.archive.org/web/20260421142223/https://bsky.app/profile/tayirdurden.bsky.social/post/3mjz6erzs5c2n
https://web.archive.org/web/20260421162009/https://bsky.app/profile/yosp-jp.bsky.social/post/3mjza72xer22n

**Comment by lindawagner** [comment]
Yes, the issue is not solved:
https://web.archive.org/web/20250624054221/https://bsky.app/profile/archive.org/post/3ldwfji7pz22q/ resolves to page not found

<img width="906" height="332" alt="Image" src="https://github.com/user-attachments/assets/1a709450-59b2-419e-a741-cabbca8914f7" />

https://web.archive.org/web/20260216135621/https://bsky.app/profile/aaronrouse.bsky.social/ resolves to page not found

<img width="959" height="398" alt="Image" src="https://github.com/user-attachments/assets/39f91fa2-b751-4eb9-bbec-47541bbc27bd" />

**Comment by ssg** [comment]
@lindawagner 2024 version opens up fine, and the latest version gives out another error, must be a regression: https://web.archive.org/web/20241222231055/https://bsky.app/profile/archive.org/post/3ldwfji7pz22q

reopning this issue for tracking.
