### ISSUE TITLE
[1.104 RC2] Android does not autocomplete handles when using @

### ISSUE THREAD

**Issue by mikekasprzak** [bluesky-social/social-app#8540]
### You're running a build that uses the React Native New Architecture, right?

- [x] I am running a build that uses the New Architecture

### Steps to Reproduce

1. Create a new post or reply. 
2. Type an `@` or `@` followed by some characters

Note that nothing ever pops up.

### Attachments

![Image](https://github.com/user-attachments/assets/6c19aa7f-0cae-46ef-a315-b7326d4da73a)

### What platform(s) does this occur on?

Android

### Device Info

Pixel 8 Pro running Android 15 revision BP1A.250505.005.B1 and the stock GBoard keyboard

### What version of the app are you using?

1.104 RC2

**Comment by mikekasprzak** [comment]
An update: It appears to work when @ is the very first character in a post or reply, but nowhere else.

**Comment by haileyok** [comment]
Believe I fixed this here. https://github.com/bluesky-social/social-app/pull/8544/commits/8196594a81be57c0402b5d807ee512a519d9f824

Can you try the latest release and see if that's working for you?

**Comment by haileyok** [comment]
(Relevant changes are https://github.com/mattermost/react-native-paste-input/pull/48)

**Comment by mikekasprzak** [comment]
Unfortunately this one is still not working. Again, typing @ as the first character in the message works, but not any other character in any other position.

**Comment by haileyok** [comment]
Oh I see now. At least the highlighting and picking works, but you're right....huh okay, thanks!
