### ISSUE TITLE
Audible hitching in the last three seconds of every single video

### ISSUE THREAD

**Issue by yahooeny** [bluesky-social/social-app#9041]
### Steps to Reproduce

Near as far as I can tell this has never been submitted to the bug tracker despite being a [frequently](https://bsky.app/profile/voicesbyzane.bsky.social/post/3lauvge3uhc2h) [commented](https://bsky.app/profile/jjstara113.bsky.social/post/3lv46ufolwk23) [on](https://bsky.app/profile/amusedunderclock.bsky.social/post/3lnns3egptc2w) [issue](https://bsky.app/profile/weaponizedbrine.bsky.social/post/3lk4vpzhohs2j) [on](https://bsky.app/profile/bikwin5.bsky.social/post/3lvwc4u4qj22z) [the](https://bsky.app/profile/waldorfsixpence.bsky.social/post/3lg6qfoss3c22) [platform](https://bsky.app/profile/retroheart.net/post/3lc423qwwzk2g) [since](https://bsky.app/profile/talkypup.com/post/3lhbvh5sp3c2k) [forever](https://bsky.app/profile/enoch.kim/post/3lg3rx2qyic2v). (Hey that last one is me!)
Every video uploaded on bluesky without fail has an audible hitch two seconds before the end of the video.
Reproduction steps:
1. Upload video to bluesky using any client
2. Watch back video and notice audio momentarily muting in the last two seconds of the video.

### What platform(s) does this occur on?

iOS, Web (Mobile), Android, Web (Desktop)

### What version of the app are you using?

Build version: 1.108.0; Bundle info: 1c85560 (prod); Bundle date: 25091107; Platform: web; Platform version: undefined; Anonymous ID: 676ecf0c-ec05-4f92-b543-76f460a1ec2e

**Comment by yahooeny** [comment]
Some examples I found just scrolling through my feed:
https://bsky.app/profile/noclipvideo.bsky.social/post/3lylyl5rjvk2e
https://bsky.app/profile/zenny.quest/post/3lytmmuf7ms26
https://bsky.app/profile/phillewis.bsky.social/post/3lytkuhtkcc2j

**Comment by yahooeny** [comment]
If you need a video to analyze:

https://enoch.kim/images/EZ2ON%20REBOOT%20-%20R%20-%202025-09-14%201-59-22%20AM%20-%20PLAY%20RECORD.mp4
```
=====================================================
Video
=====================================================
Codec 4CC:			H265
Image Size:			1280 x 720
Aspect Ratio:			1:1 (1:1)
Frame Rate:			30.003 fps
Average Bitrate:		2571 kbps
Total Duration:			00:02:16.420
Pixel format:			YUV 4:2:0, 8-bit
Color range:			Full (JPEG)
Color primaries:		BT.709
Transfer characteristics:	BT.709
Color space:			BT.709

=====================================================
Video Codec Extradata
=====================================================
Size:				133
Extradata:			01 01 40 00 00 00 90 00 00 00 00 00 78 F0 00 FC FD F8 F8 00 00 0F 03 A0 00 01 00 18 40 01 0C 01 FF FF 01 40 00 00 03 00 90 00 00 03 00 00 03 00 78 99 C0 90 A1 00 01 00 3F 42 01 01 01 40 00 00 (+69 bytes)

=====================================================
Audio (1 active track)
=====================================================
Codec:				AAC
Channels:			Stereo
Bitrate:			19598 Bps / 156 kbps
Frequency:			48000 Hz
Total Duration:			00:02:16.478

```
Video as processed and served on bluesky: https://bsky.app/profile/enoch.kim/post/3lyrvef6o322b

**Comment by surfdude29** [comment]
This may be being fixed by a PR in a private repo 🤞

![Image](https://github.com/user-attachments/assets/ef422887-18b5-4b4f-be45-0d1acdba0504)

https://bsky.app/profile/samuel.fm/post/3mgrl2gtk5s24

**Comment by mozzius** [comment]
Hello. Hopefully this should be fixed for new videos going forward (maybe) - if you see it happening again please lemme know and I can reopen this

**Comment by endrift** [comment]
still seeing something like this. I have a 5 second video I'm uploading and it hitches once partway through

**Comment by surfdude29** [comment]
Yes I also continue to see this, if you could reopen it please @mozzius 🙏

**Comment by endrift** [comment]
I checked when in the video it hitches and it is about 3 seconds before the end still

**Comment by endrift** [comment]
Also I tried multiple codecs (H.264/AAC and VP9/Opus) with the exact same result
