### ISSUE TITLE
I can't zoom-in on images in the Android app

### ISSUE THREAD

**Issue by yoav3141** [bluesky-social/social-app#9427]
### Steps to Reproduce

1. Look for a post with an image
2. Try to zoom-in with the pinching gesture
3. Nothing happens

### What platform(s) does this occur on?

Android

### Device Info

OnePlus 15

### What version of the app are you using?

1.110.0.739

**Comment by rbtnk** [comment]
Same bug on app version 1.110.1.741
Device Pixel 9
Android 16

**Comment by FuzzyFoxe** [comment]
Same here, only fix I have is temporary, and that's rebooting the device. Neither forcing the app to close or clearing cache does anything to fix it, even temporarily.
Pixel 9 Pro XL
Android 15
App version 1.110.1

**Comment by yoav3141** [comment]
looks like it is fixed

**Comment by quantheory** [comment]
Definitely not fixed, and definitely older than the OP. Using a Pixel 7 Pro, and this happens daily. Sometimes it is fixed when restarting the app, but more often even killing the app does nothing unless I restart the phone or wait a nebulous amount of time.

**Comment by quantheory** [comment]
Also, the "double tap to zoom" gesture is affected at the same time. It's not just pinching; there seems to be no way to zoom in on images.

**Comment by mozzius** [comment]
Is this still happening? I've never been able to reproduce this, unfortunately :(

**Comment by mgritter** [comment]
> Is this still happening? I've never been able to reproduce this, unfortunately :(

I experienced it today on version 1.116.0.811, on an older phone -- Android 11.

**Comment by jessedhillon** [comment]
It has never worked, in my experience (Pixel 9)

**Comment by davidcsloane** [comment]
Still happening on app v. 1.122.0 on Pixel 9

**Comment by mozzius** [comment]
Still cannot repro on any of my devices (Android 11, Android 17 beta). Any other clues you can give me? Any accessibility settings enabled?

A logcat dump would likewise be useful

**Comment by davidcsloane** [comment]
Thanks for following up so quickly! Unfortunately it's quite intermittent. When I made the comment, the app was failing to resize images for ~20 minutes, then recovered. 
It still shows up occasionally, but restarting the app, restarting the phone, or (time passing) seems to fix it.

You mentioned accessibility - I have DuckDuckGo app tracking protection turned on. I'll try turning that off for Bluesky to see if it makes a difference.
